version: '3.8'

services:
  rbxservers-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rbxservers-discord-bot
    restart: unless-stopped

    # Variables de entorno necesarias
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - COOKIE=${COOKIE}
      - CAPTCHA2=${CAPTCHA2}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - REPL_SLUG=${REPL_SLUG:-rbxservers}
      - REPL_OWNER=${REPL_OWNER:-paysencharlee}
      - PYTHONUNBUFFERED=1
      - TZ=UTC

    # Archivos de configuración y datos persistentes
    volumes:
      - ./followers.json:/app/followers.json:rw
      - ./bans.json:/app/bans.json:rw
      - ./warnings.json:/app/warnings.json:rw
      - ./user_game_servers.json:/app/user_game_servers.json:rw
      - ./users_servers.json:/app/users_servers.json:rw
      - ./vip_links.json:/app/vip_links.json:rw
      - ./delegated_owners.json:/app/delegated_owners.json:rw
      - ./roblox_cookies.json:/app/roblox_cookies.json:rw
      - ./marketplace.json:/app/marketplace.json:rw
      - ./user_coins.json:/app/user_coins.json:rw
      - ./codes_usage.json:/app/codes_usage.json:rw
      - ./promotional_codes.json:/app/promotional_codes.json:rw
      - ./user_profiles.json:/app/user_profiles.json:rw
      - ./leaderboard_data.json:/app/leaderboard_data.json:rw
      - ./startup_alerts.json:/app/startup_alerts.json:rw
      - ./maintenance_data.json:/app/maintenance_data.json:rw
      - ./music_callbacks.json:/app/music_callbacks.json:rw
      - ./user_alerts.json:/app/user_alerts.json:rw
      - ./Serversdb:/app/Serversdb:rw
      - ./RbxBotLogic:/app/RbxBotLogic:rw
      - ./attached_assets:/app/attached_assets:rw
      - ./Commands:/app/Commands:rw
      - rbxservers-data:/app/data

    # Puertos
    ports:
      - "8080:8080"  # Puerto para el servidor web interno

    # Configuración de red
    networks:
      - rbxservers-network

    # Límites de recursos
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s

    # Configuración de logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    # Configuraciones de seguridad
    security_opt:
      - no-new-privileges:true

    # Healthcheck
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  rbxservers-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# Volúmenes persistentes
volumes:
  rbxservers-data:
    driver: local