
version: '3.8'

services:
  rbxservers-bot:
    build: .
    container_name: rbxservers-discord-bot
    restart: unless-stopped
    
    # Variables de entorno necesarias
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - COOKIE=${COOKIE}
      - CAPTCHA2=${CAPTCHA2}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - REPL_SLUG=${REPL_SLUG:-rbxservers}
      - REPL_OWNER=${REPL_OWNER:-paysencharlee}
      - DISPLAY=:99
    
    # Archivos de configuración y datos persistentes
    volumes:
      - ./followers.json:/app/followers.json
      - ./bans.json:/app/bans.json
      - ./warnings.json:/app/warnings.json
      - ./user_game_servers.json:/app/user_game_servers.json
      - ./users_servers.json:/app/users_servers.json
      - ./vip_links.json:/app/vip_links.json
      - ./delegated_owners.json:/app/delegated_owners.json
      - ./roblox_cookies.json:/app/roblox_cookies.json
      - ./marketplace.json:/app/marketplace.json
      - ./user_coins.json:/app/user_coins.json
      - ./codes_usage.json:/app/codes_usage.json
      - ./promotional_codes.json:/app/promotional_codes.json
      - ./user_profiles.json:/app/user_profiles.json
      - ./leaderboard_data.json:/app/leaderboard_data.json
      - ./startup_alerts.json:/app/startup_alerts.json
      - ./maintenance_data.json:/app/maintenance_data.json
      - ./music_callbacks.json:/app/music_callbacks.json
      - ./user_alerts.json:/app/user_alerts.json
      - ./Serversdb:/app/Serversdb
      - ./RbxBotLogic:/app/RbxBotLogic
      - ./attached_assets:/app/attached_assets
    
    # Puertos
    ports:
      - "8080:8080"  # Puerto para el servidor web interno
    
    # Configuración de red
    networks:
      - rbxservers-network
    
    # Dependencias
    depends_on:
      - xvfb
    
    # Política de reinicio
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  # Servidor X virtual para Chrome headless
  xvfb:
    image: jlesage/xvfb
    container_name: rbxservers-xvfb
    restart: unless-stopped
    environment:
      - DISPLAY_WIDTH=1920
      - DISPLAY_HEIGHT=1080
    networks:
      - rbxservers-network

networks:
  rbxservers-network:
    driver: bridge

# Volúmenes persistentes opcionales
volumes:
  rbxservers-data:
    driver: local
